---
- name: Create service directory
  win_file:
    path: '{{ winsw_service_path | mandatory }}'
    state: 'directory'
    user: 'jenkins'

- name: Download service binary
  win_get_url:
    url: '{{ winsw_service_exe_url | mandatory }}'
    dest: '{{ winsw_service_exe_path | mandatory }}'
    checksum: 'sha256:{{ winsw_service_exe_sha256 | mandatory }}'
    user: '{{ winsw_service_user | mandatory }}'

- name: Download WinSW binary
  win_get_url:
    url: '{{ winsw_service_wrapper_url | mandatory }}'
    dest: '{{ winsw_service_wrapper_path | mandatory }}'
    checksum: 'sha256:{{ winsw_service_wrapper_sha256 | mandatory }}'
    user: '{{ winsw_service_user | mandatory }}'
