---
- name: Template service definition
  template:
    src: 'service.yml.j2'
    dest: '{{ winsw_service_definition }}'
    user: '{{ winsw_service_user }}'
  register: service_file

- name: Check service status
  win_command: '{{ winsw_service_wrapper_path }} status'
  register: service_status
  ignore_errors: true

- name: Stop service
  win_command: '{{ winsw_service_wrapper_path }} stopwait'
  register: service_install
  when: >
    (service_status.stdout|trim) != "NonExistent"
    and service_file.changed

- name: Uninstall service
  win_command: '{{ winsw_service_wrapper_path }} uninstall'
  register: service_install
  when: >
    (service_status.stdout|trim) != "NonExistent"
    and service_file.changed

- name: Install service
  win_command: '{{ winsw_service_wrapper_path }} install'
  when: >
    (service_status.stdout|trim) == "NonExistent"
    or service_install.changed

- name: (Re)Start service
  win_command: '{{ winsw_service_wrapper_path }} restart'
